# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_auto_20180309_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_id',
            new_name='account_risk',
        ),
    ]
