# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_auto_20180309_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_risk',
            new_name='account_id',
        ),
    ]
